### ISSUE TITLE
1.5.0 release tracker

### ISSUE THREAD

**Issue by snewcomer** [poteto/ember-changeset#301]
`1.5` Rough order of importance -

- [x] fix relationship setter
- [ ] https://github.com/poteto/ember-changeset/issues/297
- [x] https://github.com/poteto/ember-changeset/issues/281
- [x] https://github.com/poteto/ember-changeset/issues/298
- [x] https://github.com/poteto/ember-changeset/issues/282

Maybe?

- [ ] https://github.com/poteto/ember-changeset/issues/200
- [ ] https://github.com/poteto/ember-changeset/issues/209

`1.6`
- [ ] https://github.com/poteto/ember-changeset/issues/245

This is by no means final nor correct; however, I thought I would get the conversation going as I will likely start tackling a few of these over the next couple of months.  Feel free to comment, add or take any of these issues.  Would be happy to pair with anyone as well!

**Comment by snewcomer** [comment]
Note - bailing on 1.5 and moving to 1.6.  Need to fix some more inherent problems with our relay implementation.

**Comment by snewcomer** [comment]
Closing as we are on 2.0.0 track now!
